version: '3'

#Two services app where our application located and db where we store our data
services:
  app:
    #Building Dockerfile which located in the same directory 
    build: .
    #Mounted in local directory
    volumes:
      - ./:/app/
    #Declare ports
    ports:
      - 8000:8000
    #All sensitive data will store in .env.dev. In will done for security reason and it is one of best practice
    env_file:
      - ./.env.dev
    #Application depends on db
    depends_on:
      - db
  db:
    #Pulling image
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    #Declearing mount points locals and in container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #Neccessary env data which postgres need to run. Docker will look for data inside of .env.dev file
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
#Declaring volume in local to save data which will not erase when container suddenly removed.
volumes:
  postgres_data: